
services:
  django-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

    postgres:
      image: postgres:17
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - ./backend/postgres:/var/lib/postgresql/data

    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - ./redis:/data

    react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
