
services:
  postgres:
      image: postgres:17
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - ./backend/postgres:/var/lib/postgresql/data

  django-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_started
    command: bash -c "chmod +x /app/scripts/entrypoint.sh /app/scripts/initial_data_db.sh /app/scripts/wait-for-it.sh && /app/scripts/entrypoint.sh"


  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
