"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from decouple import config
from split_settings.tools import include
SECRET_KEY = "django-insecure-q&krc&pi$kukmy^sx$tv7om+&bzbd5hikn=rbjvd5-9@1)i&ex"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

include(
    "conf/i18n.py",
    "conf/timezone.py",
    "conf/db.py",
    "conf/http.py",
    "conf/templates.py",
    "conf/middleware.py",
    "conf/auth.py",
    "conf/installed_apps.py",
    "conf/misc.py",
    "conf/static.py",   
    "conf/media.py"
)
