# Generated by Django 5.2 on 2025-05-02 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cfscategory')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.cfsstatus')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cfssubcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cfstype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
