# Generated by Django 5.2 on 2025-05-02 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfs',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cfs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
