# Generated by Django 5.2 on 2025-05-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfs', '0003_cfs_date_alter_cfs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfs',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
