# Generated by Django 5.2 on 2025-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfs', '0004_alter_cfs_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfs',
            name='user',
        ),
    ]
