# Generated by Django 5.2 on 2025-05-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_cfscategory_created_at_alter_cfscategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfscategory',
            name='cfs_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dictionary.cfstype'),
        ),
        migrations.AlterField(
            model_name='cfssubcategory',
            name='cfs_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dictionary.cfscategory'),
        ),
    ]
